---
kind: pipeline
name: python-latest

steps:
  - name: notify-start
    image: python:latest
    environment:
      BOT_TOKEN:
        from_secret: bot_token
      CHAT_ID: -1001339045129
    commands:
      - ./drone.sh --start
  - name: lint
    image: python:latest
    commands:
      - pip install -r requirements.txt
      - pip install pylint
      - pylint $(find . -name "*.py")
  - name: notify
    image: python:latest
    environment:
      BOT_TOKEN:
        from_secret: bot_token
      CHAT_ID: -1001339045129
    commands:
      - ./drone.sh
    when:
      status:
      - failure
      - success